// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: db.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DatabaseService_BatchCreate_FullMethodName               = "/db.DatabaseService/BatchCreate"
	DatabaseService_BatchGet_FullMethodName                  = "/db.DatabaseService/BatchGet"
	DatabaseService_BatchUpdate_FullMethodName               = "/db.DatabaseService/BatchUpdate"
	DatabaseService_BatchDelete_FullMethodName               = "/db.DatabaseService/BatchDelete"
	DatabaseService_Query_FullMethodName                     = "/db.DatabaseService/Query"
	DatabaseService_CreateFriendRequest_FullMethodName       = "/db.DatabaseService/CreateFriendRequest"
	DatabaseService_GetFriendRequestsByUser_FullMethodName   = "/db.DatabaseService/GetFriendRequestsByUser"
	DatabaseService_UpdateFriendRequestStatus_FullMethodName = "/db.DatabaseService/UpdateFriendRequestStatus"
	DatabaseService_CreateFriendship_FullMethodName          = "/db.DatabaseService/CreateFriendship"
	DatabaseService_GetFriendships_FullMethodName            = "/db.DatabaseService/GetFriendships"
	DatabaseService_DeleteFriendship_FullMethodName          = "/db.DatabaseService/DeleteFriendship"
	DatabaseService_GetUserIdByUsername_FullMethodName       = "/db.DatabaseService/GetUserIdByUsername"
	DatabaseService_BatchCreateMessages_FullMethodName       = "/db.DatabaseService/BatchCreateMessages"
	DatabaseService_GetMessagesBetween_FullMethodName        = "/db.DatabaseService/GetMessagesBetween"
)

// DatabaseServiceClient is the client API for DatabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 数据库服务 ==========
type DatabaseServiceClient interface {
	// 用户 CRUD
	BatchCreate(ctx context.Context, in *BatchCreateRequest, opts ...grpc.CallOption) (*BatchCreateResponse, error)
	BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error)
	BatchUpdate(ctx context.Context, in *BatchUpdateRequest, opts ...grpc.CallOption) (*BatchUpdateResponse, error)
	BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// 好友请求
	CreateFriendRequest(ctx context.Context, in *CreateFriendRequestReq, opts ...grpc.CallOption) (*CreateFriendRequestRsp, error)
	GetFriendRequestsByUser(ctx context.Context, in *GetFriendRequestsByUserReq, opts ...grpc.CallOption) (*GetFriendRequestsByUserRsp, error)
	UpdateFriendRequestStatus(ctx context.Context, in *UpdateFriendRequestStatusReq, opts ...grpc.CallOption) (*UpdateFriendRequestStatusRsp, error)
	// 好友关系
	CreateFriendship(ctx context.Context, in *CreateFriendshipReq, opts ...grpc.CallOption) (*CreateFriendshipRsp, error)
	GetFriendships(ctx context.Context, in *GetFriendshipsReq, opts ...grpc.CallOption) (*GetFriendshipsRsp, error)
	DeleteFriendship(ctx context.Context, in *DeleteFriendshipReq, opts ...grpc.CallOption) (*DeleteFriendshipRsp, error)
	// 用户查询（根据 username 查 id）
	GetUserIdByUsername(ctx context.Context, in *GetUserIdByUsernameReq, opts ...grpc.CallOption) (*GetUserIdByUsernameRsp, error)
	// 消息记录
	BatchCreateMessages(ctx context.Context, in *BatchCreateMessagesReq, opts ...grpc.CallOption) (*BatchCreateMessagesRsp, error)
	GetMessagesBetween(ctx context.Context, in *GetMessagesBetweenReq, opts ...grpc.CallOption) (*GetMessagesBetweenRsp, error)
}

type databaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDatabaseServiceClient(cc grpc.ClientConnInterface) DatabaseServiceClient {
	return &databaseServiceClient{cc}
}

func (c *databaseServiceClient) BatchCreate(ctx context.Context, in *BatchCreateRequest, opts ...grpc.CallOption) (*BatchCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateResponse)
	err := c.cc.Invoke(ctx, DatabaseService_BatchCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) BatchGet(ctx context.Context, in *BatchGetRequest, opts ...grpc.CallOption) (*BatchGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetResponse)
	err := c.cc.Invoke(ctx, DatabaseService_BatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) BatchUpdate(ctx context.Context, in *BatchUpdateRequest, opts ...grpc.CallOption) (*BatchUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpdateResponse)
	err := c.cc.Invoke(ctx, DatabaseService_BatchUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) BatchDelete(ctx context.Context, in *BatchDeleteRequest, opts ...grpc.CallOption) (*BatchDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteResponse)
	err := c.cc.Invoke(ctx, DatabaseService_BatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, DatabaseService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) CreateFriendRequest(ctx context.Context, in *CreateFriendRequestReq, opts ...grpc.CallOption) (*CreateFriendRequestRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFriendRequestRsp)
	err := c.cc.Invoke(ctx, DatabaseService_CreateFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetFriendRequestsByUser(ctx context.Context, in *GetFriendRequestsByUserReq, opts ...grpc.CallOption) (*GetFriendRequestsByUserRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendRequestsByUserRsp)
	err := c.cc.Invoke(ctx, DatabaseService_GetFriendRequestsByUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) UpdateFriendRequestStatus(ctx context.Context, in *UpdateFriendRequestStatusReq, opts ...grpc.CallOption) (*UpdateFriendRequestStatusRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFriendRequestStatusRsp)
	err := c.cc.Invoke(ctx, DatabaseService_UpdateFriendRequestStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) CreateFriendship(ctx context.Context, in *CreateFriendshipReq, opts ...grpc.CallOption) (*CreateFriendshipRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFriendshipRsp)
	err := c.cc.Invoke(ctx, DatabaseService_CreateFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetFriendships(ctx context.Context, in *GetFriendshipsReq, opts ...grpc.CallOption) (*GetFriendshipsRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendshipsRsp)
	err := c.cc.Invoke(ctx, DatabaseService_GetFriendships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) DeleteFriendship(ctx context.Context, in *DeleteFriendshipReq, opts ...grpc.CallOption) (*DeleteFriendshipRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFriendshipRsp)
	err := c.cc.Invoke(ctx, DatabaseService_DeleteFriendship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetUserIdByUsername(ctx context.Context, in *GetUserIdByUsernameReq, opts ...grpc.CallOption) (*GetUserIdByUsernameRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserIdByUsernameRsp)
	err := c.cc.Invoke(ctx, DatabaseService_GetUserIdByUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) BatchCreateMessages(ctx context.Context, in *BatchCreateMessagesReq, opts ...grpc.CallOption) (*BatchCreateMessagesRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCreateMessagesRsp)
	err := c.cc.Invoke(ctx, DatabaseService_BatchCreateMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseServiceClient) GetMessagesBetween(ctx context.Context, in *GetMessagesBetweenReq, opts ...grpc.CallOption) (*GetMessagesBetweenRsp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessagesBetweenRsp)
	err := c.cc.Invoke(ctx, DatabaseService_GetMessagesBetween_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatabaseServiceServer is the server API for DatabaseService service.
// All implementations must embed UnimplementedDatabaseServiceServer
// for forward compatibility.
//
// ========== 数据库服务 ==========
type DatabaseServiceServer interface {
	// 用户 CRUD
	BatchCreate(context.Context, *BatchCreateRequest) (*BatchCreateResponse, error)
	BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error)
	BatchUpdate(context.Context, *BatchUpdateRequest) (*BatchUpdateResponse, error)
	BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// 好友请求
	CreateFriendRequest(context.Context, *CreateFriendRequestReq) (*CreateFriendRequestRsp, error)
	GetFriendRequestsByUser(context.Context, *GetFriendRequestsByUserReq) (*GetFriendRequestsByUserRsp, error)
	UpdateFriendRequestStatus(context.Context, *UpdateFriendRequestStatusReq) (*UpdateFriendRequestStatusRsp, error)
	// 好友关系
	CreateFriendship(context.Context, *CreateFriendshipReq) (*CreateFriendshipRsp, error)
	GetFriendships(context.Context, *GetFriendshipsReq) (*GetFriendshipsRsp, error)
	DeleteFriendship(context.Context, *DeleteFriendshipReq) (*DeleteFriendshipRsp, error)
	// 用户查询（根据 username 查 id）
	GetUserIdByUsername(context.Context, *GetUserIdByUsernameReq) (*GetUserIdByUsernameRsp, error)
	// 消息记录
	BatchCreateMessages(context.Context, *BatchCreateMessagesReq) (*BatchCreateMessagesRsp, error)
	GetMessagesBetween(context.Context, *GetMessagesBetweenReq) (*GetMessagesBetweenRsp, error)
	mustEmbedUnimplementedDatabaseServiceServer()
}

// UnimplementedDatabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDatabaseServiceServer struct{}

func (UnimplementedDatabaseServiceServer) BatchCreate(context.Context, *BatchCreateRequest) (*BatchCreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreate not implemented")
}
func (UnimplementedDatabaseServiceServer) BatchGet(context.Context, *BatchGetRequest) (*BatchGetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGet not implemented")
}
func (UnimplementedDatabaseServiceServer) BatchUpdate(context.Context, *BatchUpdateRequest) (*BatchUpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpdate not implemented")
}
func (UnimplementedDatabaseServiceServer) BatchDelete(context.Context, *BatchDeleteRequest) (*BatchDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDelete not implemented")
}
func (UnimplementedDatabaseServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedDatabaseServiceServer) CreateFriendRequest(context.Context, *CreateFriendRequestReq) (*CreateFriendRequestRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFriendRequest not implemented")
}
func (UnimplementedDatabaseServiceServer) GetFriendRequestsByUser(context.Context, *GetFriendRequestsByUserReq) (*GetFriendRequestsByUserRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendRequestsByUser not implemented")
}
func (UnimplementedDatabaseServiceServer) UpdateFriendRequestStatus(context.Context, *UpdateFriendRequestStatusReq) (*UpdateFriendRequestStatusRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFriendRequestStatus not implemented")
}
func (UnimplementedDatabaseServiceServer) CreateFriendship(context.Context, *CreateFriendshipReq) (*CreateFriendshipRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFriendship not implemented")
}
func (UnimplementedDatabaseServiceServer) GetFriendships(context.Context, *GetFriendshipsReq) (*GetFriendshipsRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendships not implemented")
}
func (UnimplementedDatabaseServiceServer) DeleteFriendship(context.Context, *DeleteFriendshipReq) (*DeleteFriendshipRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFriendship not implemented")
}
func (UnimplementedDatabaseServiceServer) GetUserIdByUsername(context.Context, *GetUserIdByUsernameReq) (*GetUserIdByUsernameRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserIdByUsername not implemented")
}
func (UnimplementedDatabaseServiceServer) BatchCreateMessages(context.Context, *BatchCreateMessagesReq) (*BatchCreateMessagesRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateMessages not implemented")
}
func (UnimplementedDatabaseServiceServer) GetMessagesBetween(context.Context, *GetMessagesBetweenReq) (*GetMessagesBetweenRsp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessagesBetween not implemented")
}
func (UnimplementedDatabaseServiceServer) mustEmbedUnimplementedDatabaseServiceServer() {}
func (UnimplementedDatabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeDatabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatabaseServiceServer will
// result in compilation errors.
type UnsafeDatabaseServiceServer interface {
	mustEmbedUnimplementedDatabaseServiceServer()
}

func RegisterDatabaseServiceServer(s grpc.ServiceRegistrar, srv DatabaseServiceServer) {
	// If the following call panics, it indicates UnimplementedDatabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DatabaseService_ServiceDesc, srv)
}

func _DatabaseService_BatchCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).BatchCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_BatchCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).BatchCreate(ctx, req.(*BatchCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_BatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).BatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_BatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).BatchGet(ctx, req.(*BatchGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_BatchUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).BatchUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_BatchUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).BatchUpdate(ctx, req.(*BatchUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_BatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).BatchDelete(ctx, req.(*BatchDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_CreateFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFriendRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CreateFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateFriendRequest(ctx, req.(*CreateFriendRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetFriendRequestsByUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendRequestsByUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetFriendRequestsByUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetFriendRequestsByUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetFriendRequestsByUser(ctx, req.(*GetFriendRequestsByUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_UpdateFriendRequestStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendRequestStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).UpdateFriendRequestStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_UpdateFriendRequestStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).UpdateFriendRequestStatus(ctx, req.(*UpdateFriendRequestStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_CreateFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFriendshipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).CreateFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_CreateFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).CreateFriendship(ctx, req.(*CreateFriendshipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetFriendships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendshipsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetFriendships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetFriendships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetFriendships(ctx, req.(*GetFriendshipsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_DeleteFriendship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendshipReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).DeleteFriendship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_DeleteFriendship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).DeleteFriendship(ctx, req.(*DeleteFriendshipReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetUserIdByUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserIdByUsernameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetUserIdByUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetUserIdByUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetUserIdByUsername(ctx, req.(*GetUserIdByUsernameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_BatchCreateMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).BatchCreateMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_BatchCreateMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).BatchCreateMessages(ctx, req.(*BatchCreateMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseService_GetMessagesBetween_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessagesBetweenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseServiceServer).GetMessagesBetween(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DatabaseService_GetMessagesBetween_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseServiceServer).GetMessagesBetween(ctx, req.(*GetMessagesBetweenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DatabaseService_ServiceDesc is the grpc.ServiceDesc for DatabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DatabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "db.DatabaseService",
	HandlerType: (*DatabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchCreate",
			Handler:    _DatabaseService_BatchCreate_Handler,
		},
		{
			MethodName: "BatchGet",
			Handler:    _DatabaseService_BatchGet_Handler,
		},
		{
			MethodName: "BatchUpdate",
			Handler:    _DatabaseService_BatchUpdate_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _DatabaseService_BatchDelete_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _DatabaseService_Query_Handler,
		},
		{
			MethodName: "CreateFriendRequest",
			Handler:    _DatabaseService_CreateFriendRequest_Handler,
		},
		{
			MethodName: "GetFriendRequestsByUser",
			Handler:    _DatabaseService_GetFriendRequestsByUser_Handler,
		},
		{
			MethodName: "UpdateFriendRequestStatus",
			Handler:    _DatabaseService_UpdateFriendRequestStatus_Handler,
		},
		{
			MethodName: "CreateFriendship",
			Handler:    _DatabaseService_CreateFriendship_Handler,
		},
		{
			MethodName: "GetFriendships",
			Handler:    _DatabaseService_GetFriendships_Handler,
		},
		{
			MethodName: "DeleteFriendship",
			Handler:    _DatabaseService_DeleteFriendship_Handler,
		},
		{
			MethodName: "GetUserIdByUsername",
			Handler:    _DatabaseService_GetUserIdByUsername_Handler,
		},
		{
			MethodName: "BatchCreateMessages",
			Handler:    _DatabaseService_BatchCreateMessages_Handler,
		},
		{
			MethodName: "GetMessagesBetween",
			Handler:    _DatabaseService_GetMessagesBetween_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
