// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: msg.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MsgService_RegisterOnline_FullMethodName           = "/msg.MsgService/RegisterOnline"
	MsgService_UnregisterOnline_FullMethodName         = "/msg.MsgService/UnregisterOnline"
	MsgService_SendMessage_FullMethodName              = "/msg.MsgService/SendMessage"
	MsgService_PullOfflineMessages_FullMethodName      = "/msg.MsgService/PullOfflineMessages"
	MsgService_AckOfflineMessages_FullMethodName       = "/msg.MsgService/AckOfflineMessages"
	MsgService_SendFriendRequest_FullMethodName        = "/msg.MsgService/SendFriendRequest"
	MsgService_HandleFriendRequest_FullMethodName      = "/msg.MsgService/HandleFriendRequest"
	MsgService_GetPendingFriendRequests_FullMethodName = "/msg.MsgService/GetPendingFriendRequests"
	MsgService_GetFriendList_FullMethodName            = "/msg.MsgService/GetFriendList"
	MsgService_GetHistoryMessages_FullMethodName       = "/msg.MsgService/GetHistoryMessages"
	MsgService_GetUserByToken_FullMethodName           = "/msg.MsgService/GetUserByToken"
)

// MsgServiceClient is the client API for MsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgServiceClient interface {
	// 注册/心跳在线
	RegisterOnline(ctx context.Context, in *OnlineReq, opts ...grpc.CallOption) (*OnlineReply, error)
	// 注销在线
	UnregisterOnline(ctx context.Context, in *OnlineReq, opts ...grpc.CallOption) (*OnlineReply, error)
	// 发送消息（在线直接推送，离线存 Redis）
	SendMessage(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgReply, error)
	// 拉取离线消息
	PullOfflineMessages(ctx context.Context, in *PullOfflineRequest, opts ...grpc.CallOption) (*PullOfflineReply, error)
	// 确认离线消息已接收
	AckOfflineMessages(ctx context.Context, in *AckOfflineRequest, opts ...grpc.CallOption) (*AckOfflineReply, error)
	// 发送好友请求
	SendFriendRequest(ctx context.Context, in *FriendRequestReq, opts ...grpc.CallOption) (*FriendRequestReply, error)
	// 处理好友请求（接受/拒绝）
	HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendReply, error)
	// 获取待处理的好友请求
	GetPendingFriendRequests(ctx context.Context, in *GetPendingReqsReq, opts ...grpc.CallOption) (*GetPendingReqsReply, error)
	// 获取好友列表（含在线状态）
	GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListReply, error)
	// 获取聊天历史
	GetHistoryMessages(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryReply, error)
	// 根据 token 获取用户信息（供 WebSocket 鉴权使用）
	GetUserByToken(ctx context.Context, in *GetUserByTokenReq, opts ...grpc.CallOption) (*GetUserByTokenReply, error)
}

type msgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgServiceClient(cc grpc.ClientConnInterface) MsgServiceClient {
	return &msgServiceClient{cc}
}

func (c *msgServiceClient) RegisterOnline(ctx context.Context, in *OnlineReq, opts ...grpc.CallOption) (*OnlineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineReply)
	err := c.cc.Invoke(ctx, MsgService_RegisterOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) UnregisterOnline(ctx context.Context, in *OnlineReq, opts ...grpc.CallOption) (*OnlineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineReply)
	err := c.cc.Invoke(ctx, MsgService_UnregisterOnline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SendMessage(ctx context.Context, in *SendMsgRequest, opts ...grpc.CallOption) (*SendMsgReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMsgReply)
	err := c.cc.Invoke(ctx, MsgService_SendMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) PullOfflineMessages(ctx context.Context, in *PullOfflineRequest, opts ...grpc.CallOption) (*PullOfflineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PullOfflineReply)
	err := c.cc.Invoke(ctx, MsgService_PullOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) AckOfflineMessages(ctx context.Context, in *AckOfflineRequest, opts ...grpc.CallOption) (*AckOfflineReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckOfflineReply)
	err := c.cc.Invoke(ctx, MsgService_AckOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) SendFriendRequest(ctx context.Context, in *FriendRequestReq, opts ...grpc.CallOption) (*FriendRequestReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FriendRequestReply)
	err := c.cc.Invoke(ctx, MsgService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleFriendReply)
	err := c.cc.Invoke(ctx, MsgService_HandleFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) GetPendingFriendRequests(ctx context.Context, in *GetPendingReqsReq, opts ...grpc.CallOption) (*GetPendingReqsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingReqsReply)
	err := c.cc.Invoke(ctx, MsgService_GetPendingFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) GetFriendList(ctx context.Context, in *GetFriendListReq, opts ...grpc.CallOption) (*GetFriendListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendListReply)
	err := c.cc.Invoke(ctx, MsgService_GetFriendList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) GetHistoryMessages(ctx context.Context, in *GetHistoryReq, opts ...grpc.CallOption) (*GetHistoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryReply)
	err := c.cc.Invoke(ctx, MsgService_GetHistoryMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgServiceClient) GetUserByToken(ctx context.Context, in *GetUserByTokenReq, opts ...grpc.CallOption) (*GetUserByTokenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByTokenReply)
	err := c.cc.Invoke(ctx, MsgService_GetUserByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServiceServer is the server API for MsgService service.
// All implementations must embed UnimplementedMsgServiceServer
// for forward compatibility.
type MsgServiceServer interface {
	// 注册/心跳在线
	RegisterOnline(context.Context, *OnlineReq) (*OnlineReply, error)
	// 注销在线
	UnregisterOnline(context.Context, *OnlineReq) (*OnlineReply, error)
	// 发送消息（在线直接推送，离线存 Redis）
	SendMessage(context.Context, *SendMsgRequest) (*SendMsgReply, error)
	// 拉取离线消息
	PullOfflineMessages(context.Context, *PullOfflineRequest) (*PullOfflineReply, error)
	// 确认离线消息已接收
	AckOfflineMessages(context.Context, *AckOfflineRequest) (*AckOfflineReply, error)
	// 发送好友请求
	SendFriendRequest(context.Context, *FriendRequestReq) (*FriendRequestReply, error)
	// 处理好友请求（接受/拒绝）
	HandleFriendRequest(context.Context, *HandleFriendReq) (*HandleFriendReply, error)
	// 获取待处理的好友请求
	GetPendingFriendRequests(context.Context, *GetPendingReqsReq) (*GetPendingReqsReply, error)
	// 获取好友列表（含在线状态）
	GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListReply, error)
	// 获取聊天历史
	GetHistoryMessages(context.Context, *GetHistoryReq) (*GetHistoryReply, error)
	// 根据 token 获取用户信息（供 WebSocket 鉴权使用）
	GetUserByToken(context.Context, *GetUserByTokenReq) (*GetUserByTokenReply, error)
	mustEmbedUnimplementedMsgServiceServer()
}

// UnimplementedMsgServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMsgServiceServer struct{}

func (UnimplementedMsgServiceServer) RegisterOnline(context.Context, *OnlineReq) (*OnlineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterOnline not implemented")
}
func (UnimplementedMsgServiceServer) UnregisterOnline(context.Context, *OnlineReq) (*OnlineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterOnline not implemented")
}
func (UnimplementedMsgServiceServer) SendMessage(context.Context, *SendMsgRequest) (*SendMsgReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedMsgServiceServer) PullOfflineMessages(context.Context, *PullOfflineRequest) (*PullOfflineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PullOfflineMessages not implemented")
}
func (UnimplementedMsgServiceServer) AckOfflineMessages(context.Context, *AckOfflineRequest) (*AckOfflineReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AckOfflineMessages not implemented")
}
func (UnimplementedMsgServiceServer) SendFriendRequest(context.Context, *FriendRequestReq) (*FriendRequestReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedMsgServiceServer) HandleFriendRequest(context.Context, *HandleFriendReq) (*HandleFriendReply, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFriendRequest not implemented")
}
func (UnimplementedMsgServiceServer) GetPendingFriendRequests(context.Context, *GetPendingReqsReq) (*GetPendingReqsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingFriendRequests not implemented")
}
func (UnimplementedMsgServiceServer) GetFriendList(context.Context, *GetFriendListReq) (*GetFriendListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendList not implemented")
}
func (UnimplementedMsgServiceServer) GetHistoryMessages(context.Context, *GetHistoryReq) (*GetHistoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHistoryMessages not implemented")
}
func (UnimplementedMsgServiceServer) GetUserByToken(context.Context, *GetUserByTokenReq) (*GetUserByTokenReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserByToken not implemented")
}
func (UnimplementedMsgServiceServer) mustEmbedUnimplementedMsgServiceServer() {}
func (UnimplementedMsgServiceServer) testEmbeddedByValue()                    {}

// UnsafeMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServiceServer will
// result in compilation errors.
type UnsafeMsgServiceServer interface {
	mustEmbedUnimplementedMsgServiceServer()
}

func RegisterMsgServiceServer(s grpc.ServiceRegistrar, srv MsgServiceServer) {
	// If the following call panics, it indicates UnimplementedMsgServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MsgService_ServiceDesc, srv)
}

func _MsgService_RegisterOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).RegisterOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_RegisterOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).RegisterOnline(ctx, req.(*OnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_UnregisterOnline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OnlineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).UnregisterOnline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_UnregisterOnline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).UnregisterOnline(ctx, req.(*OnlineReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_SendMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SendMessage(ctx, req.(*SendMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_PullOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullOfflineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).PullOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_PullOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).PullOfflineMessages(ctx, req.(*PullOfflineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_AckOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckOfflineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).AckOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_AckOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).AckOfflineMessages(ctx, req.(*AckOfflineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendRequestReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).SendFriendRequest(ctx, req.(*FriendRequestReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_HandleFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).HandleFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_HandleFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).HandleFriendRequest(ctx, req.(*HandleFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_GetPendingFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingReqsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).GetPendingFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_GetPendingFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).GetPendingFriendRequests(ctx, req.(*GetPendingReqsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_GetFriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).GetFriendList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_GetFriendList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).GetFriendList(ctx, req.(*GetFriendListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_GetHistoryMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).GetHistoryMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_GetHistoryMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).GetHistoryMessages(ctx, req.(*GetHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgService_GetUserByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServiceServer).GetUserByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgService_GetUserByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServiceServer).GetUserByToken(ctx, req.(*GetUserByTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgService_ServiceDesc is the grpc.ServiceDesc for MsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "msg.MsgService",
	HandlerType: (*MsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterOnline",
			Handler:    _MsgService_RegisterOnline_Handler,
		},
		{
			MethodName: "UnregisterOnline",
			Handler:    _MsgService_UnregisterOnline_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _MsgService_SendMessage_Handler,
		},
		{
			MethodName: "PullOfflineMessages",
			Handler:    _MsgService_PullOfflineMessages_Handler,
		},
		{
			MethodName: "AckOfflineMessages",
			Handler:    _MsgService_AckOfflineMessages_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _MsgService_SendFriendRequest_Handler,
		},
		{
			MethodName: "HandleFriendRequest",
			Handler:    _MsgService_HandleFriendRequest_Handler,
		},
		{
			MethodName: "GetPendingFriendRequests",
			Handler:    _MsgService_GetPendingFriendRequests_Handler,
		},
		{
			MethodName: "GetFriendList",
			Handler:    _MsgService_GetFriendList_Handler,
		},
		{
			MethodName: "GetHistoryMessages",
			Handler:    _MsgService_GetHistoryMessages_Handler,
		},
		{
			MethodName: "GetUserByToken",
			Handler:    _MsgService_GetUserByToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "msg.proto",
}
